### ISSUE TITLE
GIT Fetch Fail

### ISSUE THREAD

**Issue by darren131** [shipitjs/shipit#116]
Hi,

I'm having a problem where deploying dies around the git fetch bit – and I have no idea what the deal is. Running latest ver of git (2.7.2) on OS X. Any help would be greatly appreciated!

Error
---

```
'deploy:fetch' errored after 33 s
Error: Command failed: /bin/sh -c git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"
From bitbucket.org:crafttheweb/nzb.co.nz
 * [new branch]      browserify -> shipit/browserify
 * [new branch]      data-table-4 -> shipit/data-table-4
 * [new branch]      master     -> shipit/master
 * [new branch]      navigation -> shipit/navigation
 * [new branch]      new-popovers -> shipit/new-popovers
 * [new branch]      table-scroll -> shipit/table-scroll

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

shipit.js file
---
```
module.exports = function (shipit) {

    require('shipit-deploy')(shipit);
    // require('shipit-shared')(shipit);
    require('shipit-npm')(shipit);
    var mailer = require('./source/lib/deploy-emailer');
    var mailOptions = require('./source/lib/mailoptions.json');

    shipit.initConfig({
        default: {
            workspace: '/tmp/nzb',
            deployTo: '/srv/www/patterns.nzb.thefold.co.nz',
            repositoryUrl: 'git@bitbucket.org:crafttheweb/nzb.co.nz.git',
            ignores: ['.git', 'node_modules','bower_components','sass'],
            keepReleases: 2,
            shallowClone: true,
            npm: {
                remote: false
            }
        },
        staging: {
            servers: 'patterns.nzb.thefold.co.nz',
        }
    });

    shipit.on('npm_installed',function(){
        shipit.start('build');
    });


    shipit.blTask('build', function() {
        return shipit.local('npm run build', {cwd:shipit.config.workspace});
    });

    shipit.on('published',function(){
        mailer(mailOptions);
    });
};
```

**Comment by darren131** [comment]
This seems to fix it:
https://github.com/shipitjs/shipit-deploy/issues/108#issuecomment-187969369

Hopefully no other issues because of that change...?
