### ISSUE TITLE
Deploy:fetch errored

### ISSUE THREAD

**Issue by jsdario** [shipitjs/shipit#121]
Hi, I need some help debugging the following stack trace. Seems to be a local problem and it does not show a lot of info.

```
'deploy:fetch' errored after 4.07 s
Error: Command failed: /bin/sh -c git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"
Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
From github.com:jsdario/netbeast-api
 * [new branch]      master     -> shipit/master
 * [new branch]      production -> shipit/production
 * [new branch]      stage      -> shipit/stage

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by biperch** [comment]
Hi, I have the same problem

I have difficulty working through the SSH, while working through HTTPS so good

my config
```
module.exports = function (shipit) {
  require('shipit-deploy')(shipit);
  shipit.initConfig({

    default: {
      workspace: '/tmp/github-monitor-2',
      deployTo: '/tmp/deploy_to',
      repositoryUrl: 'git@bitbucket.org:blackflagsoft/der.git', // ssh or https
      ignores: ['.git', 'node_modules'],
      keepReleases: 2,
      deleteOnRollback: false,
      key: '/home/biperch/.ssh',
      shallowClone: true
    },

    staging: {
      servers: 'biperch@server.ru:2222'
    }
  });
};
```
Log
```
biperch@biperch-desktop:~/project/test_iskyweb$ shipit staging  deploy

Running 'deploy:init' task...
Finished 'deploy:init' after 4.67 ms

Running 'deploy:fetch' task...
Deleting existing workspace "/tmp/github-monitor-2"
Running "rm -rf /tmp/github-monitor-2" on local.
Create workspace "/tmp/github-monitor-2"
Workspace created.
Initialize local repository in "/tmp/github-monitor-2"
Running "git init" on local.
@ Инициализирован пустой репозиторий Git в /tmp/github-monitor-2/.git/
Repository initialized.
List local remotes.
Running "git remote" on local.
Update remote "git@bitbucket.org:blackflagsoft/der.git" to local repository "/tmp/github-monitor-2"
Running "git remote add shipit git@bitbucket.org:blackflagsoft/der.git" on local.
Remote updated.
Fetching repository "git@bitbucket.org:blackflagsoft/der.git"
Running "git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"" on local.
@ Из bitbucket.org:blackflagsoft/der
@  * [новая ветка]     biperch-dev2 -> shipit/biperch-dev2
@  * [новая ветка]     biperch-dev3 -> shipit/biperch-dev3
@  * [новая ветка]     biperch-dev5 -> shipit/biperch-dev5
@  * [новая ветка]     develop    -> shipit/develop
@  * [новая ветка]     kirill2kostia -> shipit/kirill2kostia
@  * [новая ветка]     kirill_3   -> shipit/kirill_3
@  * [новая ветка]     kirillos   -> shipit/kirillos
@  * [новая ветка]     kirillos2  -> shipit/kirillos2
@  * [новая ветка]     kot-work1  -> shipit/kot-work1
@  * [новая ветка]     kot-works  -> shipit/kot-works
@  * [новая ветка]     kot_work_home -> shipit/kot_work_home
@  * [новая ветка]     master     -> shipit/master
'deploy:fetch' errored after 16 s
Error: Command failed: git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"
Из bitbucket.org:blackflagsoft/der
 * [новая ветка]     biperch-dev2 -> shipit/biperch-dev2
 * [новая ветка]     biperch-dev3 -> shipit/biperch-dev3
 * [новая ветка]     biperch-dev5 -> shipit/biperch-dev5
 * [новая ветка]     develop    -> shipit/develop
 * [новая ветка]     kirill2kostia -> shipit/kirill2kostia
 * [новая ветка]     kirill_3   -> shipit/kirill_3
 * [новая ветка]     kirillos   -> shipit/kirillos
 * [новая ветка]     kirillos2  -> shipit/kirillos2
 * [новая ветка]     kot-work1  -> shipit/kot-work1
 * [новая ветка]     kot-works  -> shipit/kot-works
 * [новая ветка]     kot_work_home -> shipit/kot_work_home
 * [новая ветка]     master     -> shipit/master

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
```

**Comment by prasanth-cubettech** [comment]
Please remove "shallowClone: true" and run again

**Comment by biperch** [comment]
@prasanth-cubettech Thanks

**Comment by dcp3450** [comment]
For anyone who come across this issue (I know it's closed but Google is a magical wizard). My config set to `shallowClone: false` and switched it to `shallowClone: true` and it shipped. Not 100% what that config is doing (I didn't put ours together) but switching that setting made these errors stop and finally ship:

`'deploy:fetch' errored after 1.29 s
Error: Command failed: git fetch shipit --prune && git fetch shipit --prune "refs/tags/*:refs/tags/*"
fatal: missing blob object '#####################'
error: github.com:themorrisonagency/samsung-microsite.git did not send all necessary objects`
