### ISSUE TITLE
shipit.remote options.cwd can't work well

### ISSUE THREAD

**Issue by DuanPengfei** [shipitjs/shipit#142]
Does `shipit.remote options` support `cwd`?

```
shipit.remote('ls -al', { cwd: '~/.ssh' }, function (error) {
    if (error) {
        console.log(error);
    }
});
```
```
{ Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs:
   [ '-c',
     'ssh -i /home/vagrant/.ssh/id_rsa vagrant@192.168.33.101 "ls -al"' ],
  cmd: 'ssh -i /home/vagrant/.ssh/id_rsa vagrant@192.168.33.101 "ls -al"' }
```

**Comment by timkelty** [comment]
The `cwd` option only applies to local.
There is an issue for making this work on remote here: https://github.com/shipitjs/shipit/issues/9

**Comment by DuanPengfei** [comment]
👌
