### ISSUE TITLE
Deploy failing at reset HEAD

### ISSUE THREAD

**Issue by dcp3450** [shipitjs/shipit#172]
When running the `npm run shipit -- staging deploy` command It fails with this error:

`Running "git reset --hard HEAD" on local.
@ error: unable to read sha1 file of dist/img/products.jpg (0cc0782c43e7bc6ea4d7b8d8b7cf740cd5a9ca91)
@ fatal: Could not reset index file to revision 'HEAD'.
'deploy:fetch' errored after 1.31 s
Error: Command failed: git reset --hard HEAD
error: unable to read sha1 file of dist/img/products.jpg (0cc0782c43e7bc6ea4d7b8d8b7cf740cd5a9ca91)
fatal: Could not reset index file to revision 'HEAD'.
    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

**Comment by neoziro** [comment]
Probably a too old git version?
