### ISSUE TITLE
FIXED: potentially unsafe regular expression(edit:EDIT: This has been fixed)

### ISSUE THREAD

**Issue by JaeWanSeol** [shipitjs/shipit#175]
Hello, I am new to shipit. Recently I installed 'shipit-cli' and 'shipit-deploy'.

I used this command. "npm install -g shipit-cli"(to install globally) "npm install shipit-deploy"(to install locally in my project)
And to deploy my project, I typed "shipit staging deploy". But I met error message. Total error message is below. How can I deal with this error message?

/Users/bmy4415/.nvm/versions/node/v8.9.4/lib/node_modules/shipit-cli/node_modules/regex-not/index.js:62
    throw new Error('potentially unsafe regular expression: ' + res);
    ^

Error: potentially unsafe regular expression: ^(?:(?!(?:[\[!*+?$^"'.\\/]+)).)+
    at Function.toRegex.create (/Users/bmy4415/.nvm/versions/node/v8.9.4/lib/node_modules/shipit-cli/node_modules/regex-not/index.js:62:11)
    at createTextRegex (/Users/bmy4415/.nvm/versions/node/v8.9.4/lib/node_modules/shipit-cli/node_modules/nanomatch/lib/parsers.js:378:22)
    at Object.<anonymous> (/Users/bmy4415/.nvm/versions/node/v8.9.4/lib/node_modules/shipit-cli/node_modules/nanomatch/lib/parsers.js:14:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)

**Comment by jonschlinkert** [comment]
This has been fixed:

- delete `node_modules`
- reinstall everything and make sure that npm or yarn don't use cached modules

**Comment by JaeWanSeol** [comment]
Where path do you mean? "/Users/bmy4415/.nvm/versions/node/v8.9.4/lib/node_modules" or "Users/bmy4415/.nvm/versions/node/v8.9.4/lib/node_modules/shipit-cli/node_modules"

**Comment by jonschlinkert** [comment]
@JaeWanSeol might I suggest that you update the issue per https://github.com/shipitjs/shipit/issues/175#issuecomment-366850970, and lock it to prevent follow-on comments that make it harder to find the solution?

**Comment by JaeWanSeol** [comment]
Sure, I changed issue title and how can i lock comment?

**Comment by jonschlinkert** [comment]
I think a ship-it maintainer will need to do that, sorry I wasn't clear about that. My comment has been updated.

**Comment by JaeWanSeol** [comment]
Thanks a lot. Have a nice day.

**Comment by jonschlinkert** [comment]
Np, @JaeWanSeol. you can close this issue now.
