### ISSUE TITLE
4.0.1 - ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by mpochron** [shipitjs/shipit#178]
```
Running "cd /var/www/html/releases/20180318215420 && tar --strip-components=1 -xzf tmp-115Xe9I6rcuYkZi.tar.gz" on host "host.example.com".
Running "cd /var/www/html/releases/20180318215420 && rm tmp-115Xe9I6rcuYkZi.tar.gz" on host "host.example.com".
'deploy:update' errored after 1.63 min
TypeError [ERR_INVALID_ARG_TYPE]: The "list" argument must be one of type Array, Buffer, or Uint8Array
    at Function.concat (buffer.js:471:13)
    at /usr/local/share/.config/yarn/global/node_modules/ssh-pool/lib/Connection.js:449:26
    at Array.reduce (<anonymous>)
    at /usr/local/share/.config/yarn/global/node_modules/ssh-pool/lib/Connection.js:447:22
    at Generator.next (<anonymous>)
    at step (/usr/local/share/.config/yarn/global/node_modules/ssh-pool/lib/Connection.js:43:191)
    at /usr/local/share/.config/yarn/global/node_modules/ssh-pool/lib/Connection.js:43:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

```

**Comment by neoziro** [comment]
Can you give your `shipitfile.js` please?

**Comment by mpochron** [comment]
I downgrade from 4.0.1 to 3.0.0, and well works.

**Comment by mpochron** [comment]
This about shipit-cli.
