### ISSUE TITLE
Error: Command failed: git checkout undefined

### ISSUE THREAD

**Issue by andrewhl** [shipitjs/shipit#188]
I had a working shipit deployment. Today it started giving me the following error:

```bash
Remote updated.
Fetching repository "git@github.com:me/myapp.git"
Running "git fetch shipit --prune --depth=1 && git fetch shipit --prune "refs/tags/*:refs/tags/*"" on local.
@ From github.com:me/myapp.git
@  * [new branch]      develop              -> shipit/develop
@  * [new branch]      master               -> shipit/master
Repository fetched.
Checking out commit-ish "undefined"
Running "git checkout undefined" on local.
@ error: pathspec 'undefined' did not match any file(s) known to git.
'deploy:fetch' errored after 1.03 min
Error: Command failed: git checkout undefined
error: pathspec 'undefined' did not match any file(s) known to git.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

node: v8.11.1
npm: 5.6.0
shipit-deploy: ^2.5.1
shipit: 4.0.1

Not sure what's changed. I recently upgraded my local node from v8.0.0 to 8.11.1.

Here's my `shipitfile.js`:

```javascript
module.exports = shipit => {
    require('shipit-deploy')(shipit);

    shipit.initConfig({
        default: {
            workspace: '/tmp/github-monitor',
            deployTo: '~/apps/myapp',
            repositoryUrl: 'git@github.com:me/myapp.git',
            ignores: ['.git', 'node_modules'],
            rsync: ['--del'],
            keepReleases: 2,
            key: '~/.ssh/mykey',
            shallowClone: true,
        },
        production: {
            servers: 'me@myserver.org',
        },
    });

    shipit.task('start', function() {
        shipit.log('Installing...');
        let promise1 = shipit.remote('cd ~/apps/myapp/current && yarn');
        let promise2 = promise1.then(function(res) {
            shipit.log('Building...');
            shipit.remote('cd ~/apps/myapp/current && npm run build');
        });
        let promise3 = promise2.then(function(res) {
            shipit.log('Copying Environment File...');
            shipit.remote('cp ~/apps/myapp/shared/.env ~/apps/myapp/current');
        });
        promise3.then(function(res) {
            shipit.log('Starting...');
            shipit.remote(
                'pm2 delete server && pm2 start ~/apps/myapp/current/server.js --name "server"'
            );
        });
    });
};
```

**Comment by andrewhl** [comment]
I needed to specify a branch in `shipit.initConfig`:

```javascript
    shipit.initConfig({
        default: {
            workspace: '/tmp/github-monitor',
            deployTo: '~/apps/myapp',
            repositoryUrl: 'git@github.com:me/myapp.git',
            ignores: ['.git', 'node_modules'],
            rsync: ['--del'],
            keepReleases: 2,
            key: '~/.ssh/mykey',
            shallowClone: true,
            branch: 'master',
        },
        production: {
            servers: 'me@myserver.org',
        },
    });
```
