### ISSUE TITLE
Arguments to path.join must be strings

### ISSUE THREAD

**Issue by minhchu** [shipitjs/shipit#204]
When I forget to define `deployTo` option, it throws this error:

```
$ shipit staging deploy

Running 'deploy:init' task...
'deploy:init' errored after 385 μs
TypeError: Arguments to path.join must be strings
    at Object.module.exports [as join] (/home/minhchu/myproject/node_modules/path2/posix/join.js:10:10)
    at extendShipit (/home/minhchu/myproject/node_modules/shipit-deploy/lib/extendShipit.js:65:40)
    at Shipit._shipitUtils2.default.registerTask (/home/minhchu/myproject/node_modules/shipit-deploy/lib/tasks/deploy/init.js:21:32)
    at module.exports (/home/minhchu/myproject/node_modules/orchestrator/lib/runTask.js:34:7)
    at Shipit.Orchestrator._runTask (/home/minhchu/myproject/node_modules/orchestrator/index.js:273:3)
    at Shipit.Orchestrator._runStep (/home/minhchu/myproject/node_modules/orchestrator/index.js:214:10)
    at Shipit.Orchestrator.start (/home/minhchu/myproject/node_modules/orchestrator/index.js:134:8)
    at /home/minhchu/myproject/node_modules/shipit-cli/lib/cli.js:45:14
    at next (native)
    at step (/home/minhchu/myproject/node_modules/shipit-cli/lib/cli.js:84:191)
    at /home/minhchu/myproject/node_modules/shipit-cli/lib/cli.js:84:361
    at process._tickCallback (internal/process/next_tick.js:109:7)
error Command failed with exit code 1.
```
We may check required options and throw some friendly warnings first

**Comment by ravensnowbird** [comment]
Having the same issue.
