### ISSUE TITLE
Deply fails if the previous build directory has been removed manually

### ISSUE THREAD

**Issue by richrd** [shipitjs/shipit#213]
Could it just ignore the previous releases if they don't exist? This is the error that occurs:

```
Error: Command failed: ssh -i /home/user/.ssh/id_rsa deployment@example.com "cp -a /var/www/project/releases/20180829065949/. /var/www/project/releases/20180829113223"
cp: cannot stat '/var/www/project/releases/20180829065949/.': No such file or directory

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by neoziro** [comment]
I think we could do it. I am open to a PR for that.

**Comment by richrd** [comment]
Great! How should this be done? Maybe we could add a flag something like `ignoreErrors` to `remote`, and use that here https://github.com/shipitjs/shipit/blob/6ba6f0077b5a677aaf5b27bcffb419e142f67178/packages/shipit-deploy/src/tasks/deploy/update.js#L32 ?

This is what I'm refering to with `remote` https://github.com/shipitjs/shipit/blob/6ba6f0077b5a677aaf5b27bcffb419e142f67178/packages/shipit-cli/src/Shipit.js#L210

**Comment by utkarsh-dixit** [comment]
Was this issue resolved? If not I'd like to fix it.

**Comment by neoziro** [comment]
@utkarsh-dixit no it is not resolved, feel free to fix it.
