### ISSUE TITLE
Removing workspace "undefined" error - AssertionError [ERR_ASSERTION]: rimraf: missing path

### ISSUE THREAD

**Issue by asgeo1** [shipitjs/shipit#218]
Hi there,

I'm getting the following error:
```
Removing workspace "undefined"
'deploy:update' errored after 14 s
AssertionError [ERR_ASSERTION]: rimraf: missing path
    at rimraf (/Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/rimraf/rimraf.js:50:3)
    at Promise (/Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/rmfr/index.js:25:2)
    at new Promise (<anonymous>)
    at promisifiedRimraf (/Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/rmfr/index.js:24:50)
    at rmfr (/Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/rmfr/index.js:119:9)
    at /Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/shipit-deploy/lib/tasks/deploy/update.js:196:34
    at Generator.next (<anonymous>)
    at step (/Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/shipit-deploy/lib/tasks/deploy/update.js:39:191)
    at /Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/shipit-deploy/lib/tasks/deploy/update.js:39:437
    at new Promise (<anonymous>)
    at /Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/shipit-deploy/lib/tasks/deploy/update.js:39:99
    at removeWorkspace (/Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/shipit-deploy/lib/tasks/deploy/update.js:201:22)
    at Shipit.<anonymous> (/Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/shipit-deploy/lib/tasks/deploy/update.js:213:11)
    at Generator.next (<anonymous>)
    at step (/Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/shipit-deploy/lib/tasks/deploy/update.js:39:191)
    at /Users/asgeo1/Projects/fshop/mypostlabels-shopfront/node_modules/shipit-deploy/lib/tasks/deploy/update.js:39:361
```

My config:
```
  shipit.initConfig({
    default: {
      rsyncFrom: './',
      dirToCopy: 'dist',
      deployTo: '/home/deploy/apps/xxx',
      keepReleases: 5,
      deleteOnRollback: false
    },
    staging: {
      servers: 'deploy@xxx.com'
    },
    production: {
      servers: 'deploy@xxx.com'
    }
  })
```

The bug is that it assumes `shipit.workspace` will not be undefined. However it can actually be undefined if you're not using git and are just copying local files to the server.

I can already see that it's been fixed here:

https://github.com/shipitjs/shipit/pull/200

When can we get a new version released?

**Comment by neoziro** [comment]
It has been released. Sorry for the delay!
