### ISSUE TITLE
Failed to run custom task - task not defined error

### ISSUE THREAD

**Issue by masterkorp** [shipitjs/shipit#40]
Hello,

I was trying to run a custom task to test the ``shipit.on`` method.
Here is my ``shipitfile.js``:
```javascript
module.exports = function (shipit) {
  require('shipit-deploy')(shipit);

  shipit.initConfig({
    default: {
      workspace: '/tmp/deploy/test-workspace',
      deployTo: '/tmp/deploy/test-myapp',
      repositoryUrl: 'git@git.com:myorganization/myrepo.git',
      ignores: ['.git', 'node_modules'],
      keepReleases: 5,
      //key: '/path/to/key',
      shallowClone: true
    },
    staging: {
      servers: 'myuser@myserver.mydomain.com'
    }
  });

  shipit.task('pwd', function () {
    return shipit.remote('pwd');
  });

  shipit.on('published', function () {
    task.run(['pwd'])
  });
};
```

But I get this.
```
Release published.
'deploy:publish' errored after 1.95 s
ReferenceError: task is not defined
    at Shipit.<anonymous> (/home/myuser/path/to/myrepo/shipitfile.js:26:5)
    at Shipit.EventEmitter.emit (events.js:104:17)
    at /home/myuser/path/to/myrepo/node_modules/shipit-deploy/tasks/deploy/publish.js:19:14
    at /home/myuser/path/to/myrepo/node_modules/shipit-cli/node_modules/ssh-pool/node_modules/promise/lib/core.js:33:15
    at flush (/home/myuser/path/to/myrepo/node_modules/shipit-cli/node_modules/ssh-pool/node_modules/promise/node_modules/asap/asap.js:27:13)
```

How am I supposed to declare a task ?

**Comment by masterkorp** [comment]
Ok, I just realized that the ``task```object does no exist.

Using ``shipit.start`` works.

I am closing this issue, apologies for the noise.
