### ISSUE TITLE
"Error: you need to resolve your current index first"

### ISSUE THREAD

**Issue by kjbrum** [shipitjs/shipit#67]
Not sure if I'm doing something wrong. Getting this error after the repository is fetched...

```
Repository fetched.
Checking out commit-ish "master"
Running "git checkout master" on local.
@ error: you need to resolve your current index first
@ package.json: needs merge
'deploy:fetch' errored after 946 ms
Error: Command failed: error: you need to resolve your current index first

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:117:20)
    at Pipe.close (net.js:466:12)
Unhandled rejection Error: Command failed: error: you need to resolve your current index first

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:117:20)
    at Pipe.close (net.js:466:12)
```

Any help would be greatly appreciated, would love to get this working.

**Comment by vlkosinov** [comment]
Can you post your config? 
It seems you have made some custom changes in workspace directory Try to remove it or set shallowClone options to true.

**Comment by kjbrum** [comment]
Using shallowClone fixed the issue. Thanks!
